name: triptolemus
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_emoji: ^2.5.1
  get: ^4.6.6
  glowy_borders: ^1.0.2
  keyboard_detection: ^0.7.0
  page_transition: ^2.1.0
  path: ^1.8.3
  provider: ^6.1.1
  sqflite: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/test.jpeg
    - assets/logo1.jpeg
